apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: wny2naa6i-nodejs 
  janus-idp.io/tekton: wny2naa6i-nodejs
  backstage.io/kubernetes-id: wny2naa6i-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wny2naa6i-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml