apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wny2naa6i-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wny2naa6i-nodejs 
  name: wny2naa6i-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wny2naa6i-nodejs 
